apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerinformation-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp-container
          image: rizvana13/sampleapp:0.1
          ports:
            - containerPort: 8080
